version: "3.8"
services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "5000:80"
    networks:
      - backend
      - frontend
  result:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
    restart: on-failure
    networks:
      - backend
      - frontend
  worker:
    build: ./worker
    networks:
      - backend
  redis:
    image: redis:latest
    networks:
      - backend
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    networks:
      - backend

volumes:
  postgres_data:
networks:
  frontend:
  backend:
